[package]
name = "ruby-analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ruby-analyzer"
path = "src/main.rs"

[dependencies]
ruby-prism = "1.2.0"

[dev-dependencies]
glob = "0.3.1"
toml = "0.8.19"
yaml-rust = "0.4.5"
